<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet Package Metadata -->
    <PackageId>AxisEndpoints</PackageId>
    <Version>1.0.0</Version>
    <Title>AxisEndpoints</Title>
    <Description>A library for implementing the Request-Endpoint-Response pattern in ASP.NET Core, based on Minimal API</Description>
    <Authors>Sheepla</Authors>
    <PackageProjectUrl>https://github.com/sheepla/AxisEndpoints</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/sheepla/AxisEndpoints</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>asp-net-core;repr-pattern;endpoints;vertical-slice-architecture;openapi</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <!-- Required for using types ASP.NET Core types e.g. WebApplication, IHttpContextAccessor -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AxisEndpoints.Tests" />
  </ItemGroup>
</Project>
